project:
  type: website
  output-dir: docs

website:
  # cookie-consent:
  #   type: implied
  #   style: standalone
  #   palette: light
  google-analytics:
    tracking-id: "G-W9H0V3N3EJ"
    anonymize-ip: true
  title: "Davide Rossetti"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



