project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!ignored-dir/"

execute:
  freeze: auto  # Re-render only when source changes

website:
  #   type: implied
  #   style: standalone
  #   palette: light
  google-analytics:
    tracking-id: "G-W9H0V3N3EJ"
    anonymize-ip: true
  title: "Davide Rossetti"
  description: "Personal website of Davide Rossetti"
  site-url: "https://daviderossetti.net"
  repo-url: "https://github.com/Lulliter/daviderossetti"
#  repo-actions: [edit, issue]
  favicon: images/net2.png
  search: false # no magnifier on navbar
  announcement:
    icon: cone-striped
    dismissable: true
    content: "Website under construction"
    type: warning
    position: below-navbar
  page-footer:
    left: |
      {{< fa copyright >}} Davide Rossetti 2025
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)
#      [Code at {{< fa brands github >}} GitHub]({{< var websites.gh_repo >}})

  navbar:
    # logo: images/TAIS.png

    right:
      - href: index.qmd
        icon: house-door-fill
        text: " "
      - href: portfolio/index.qmd
        text: "Portfolio"
      - href: news.qmd
        text: "News"



format:
  html:
    toc: true
    toc-location: "left"
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    fontsize: 1em
    theme: theme/davides_theme.scss
    # css: theme/styles.css
    ##----- code highlighting style
    highlight-style: monokai # atom-one # github # dracula
    mainfont: "Lato"
    monofont: "Fira Mono"


